---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy-light }

platform: linux

inputs:
  - name: tarballs
  - name: cf-app-sd-ci
  - name: deployments-repo

run:
  path: cf-app-sd-ci/ci/tasks/upload-release-tarball

params:
  ENVIRONMENT_NAME: ~
