---
image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/deploy
    tag: latest

platform: linux

inputs:
  - name: bbl-state
  - name: cf-deployment-concourse-tasks
  - name: local-release

run:
  path: cf-app-sd-release/ci/tasks/upload-local-release

params:
  BBL_STATE_DIR:
